version: '3.8'
services:
  web:
    container_name: leave-migration-ui
    build:
      context: ./frontend
      args:
        app_env: production
    image: digio/migrate-leave-to-xero-web:latest
    restart: always
    env_file:
      - .env
    volumes:
      - './frontend/src:/frontend/src'
      - '/tmp:/tmp'
    ports:
      - "3000:3000"
  api:
    container_name: leave-migration-api
    build:
      context: .
    image: digio/migrate-leave-to-xero-api:latest
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - '.:/app'
      - '/tmp:/tmp'

  blackboxapi:
    container_name: blackboxapi
    hostname: blackboxapi
    build:
      context: .
      dockerfile: ./test/blackbox/Dockerfile
    restart: always
    env_file:
      - ./test/blackbox/.env
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - '.:/app'
      - '/tmp:/tmp'
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://blackboxapi:8000/health" ]
#      timeout: 10s
#      interval: 1s
#      retries: 5

  blackbox:
    depends_on:
      - blackboxapi
    build:
      context: .
      dockerfile: Dockerfile.blackbox
    env_file:
      - test/blackbox/.env
    environment:
      - SERVER_URL=blackboxapi:8080
    volumes:
      - '.:/app'
    links:
      - blackboxapi

