version: '3.7'
services:
  web:
    container_name: leave-migration-ui
    build:
      context: ./frontend
      args:
        app_env: production
    image: digio/migrate-leave-to-xero-web:latest
    restart: always
    env_file:
      - .env
    volumes:
      - './frontend/src:/frontend/src'
      - '/tmp:/tmp'
    ports:
      - 3000:3000
  api:
     container_name: leave-migration-api
     build:
       context: .
     image: digio/migrate-leave-to-xero-api:latest
     restart: always
     env_file:
       - .env
     ports:
       - 8000:8000
     volumes:
       - '.:/app'
       - '/tmp:/tmp'
