name: reviewdog
on: [pull_request]
jobs:
  misspell:
    name: misspell detect
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v2
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
  go:
    name: gofmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: gofmt -w -s .
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: gofmt